# Generated by Django 5.2.5 on 2025-10-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'New App', 'verbose_name_plural': 'New Apps'},
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='data',
            new_name='date',
        ),
    ]
