# Generated by Django 5.2.8 on 2026-01-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0002_articles_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
